name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
      - run: npm run lint
      - run: npx tsc --noEmit
      - run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test

  e2e:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: rental_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
      - run: npx playwright install chromium --with-deps
      - run: npx prisma db push
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
      - run: npx prisma db seed
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
      - run: npm run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
          NEXTAUTH_SECRET: ci-e2e-secret-key
          NEXTAUTH_URL: http://localhost:3000
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
      - run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:postgrespassword@localhost:5432/rental_test
          NEXTAUTH_SECRET: ci-build-secret-key
          NEXTAUTH_URL: http://localhost:3000
